version: "3"
services:

  travel_app:
    image: travel-app
    build:
      context: travelapp
    ports:
      - "8085:8080"
    volumes:
      - "travelapp:/travelapp"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/travel_app
    dependson:
      - travel_db

  travel_db:
    image: travel-db
    build:
      context: SqlQueries
    ports:
      - "3306:3306"
    volumes:
      - "traveldb:/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    stdin_open: true
    tty: true


volumes:
  travelapp:
  traveldb:
