version: "3"
services:

  travel_app:
    container_name: travel-app
    image: travel-app
    build:
      context: travelapp
    ports:
      - "8085:8080"
    volumes:
      - "travelapp:/travelapp"
    networks:
      - travel-application
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/travel_app

  travel_db:
    container_name: travel-db
    image: travel-db
    build:
      context: SqlQueries
    ports:
      - "3306:3306"
    volumes:
      - "traveldb:/mysql"
    networks:
      - travel-application
    environment:
      MYSQL_ROOT_PASSWORD: 1234

networks:
  travel-application:

volumes:
  travelapp:
  traveldb: